name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  who:
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time:
    description: 'The time we greeted you'
  example:
    description: 'The response from example.com'
runs:
  using: 'node12'
  main: 'index.js'